version: 2

updates:
  - package-ecosystem: gomod
    directories:
      - /
      - /go/resources/tools
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      gomod:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
