language: clang
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - lcov

install:
  - gem install coveralls-lcov

script:
  - cd c && make test

after_success:
  - coveralls-lcov /home/travis/build/tecnickcom/farmhash64/c/target/test/coverage/farmhash64.info
