os: linux
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - lcov
    - astyle
    - devscripts
    - python
    - python-pip
    - python-autopep8
    - doxygen
install:
  - gem install coveralls-lcov

matrix:
  include:
    - language: c
      script:
        - cd c && make all
      after_success:
        - coveralls-lcov /home/travis/build/tecnickcom/farmhash64/c/target/test/coverage/farmhash64.info
    - language: go
      script:
        - cd go && make all
    - language: go
      script:
        - cd cgo && make all
    - language: python
      script:
        - cd python && make all
      
