package:
  name: farmhash64
  version: 1.2.0.1

source:
  path: ..

requirements:
  host:
    - python
    - setuptools
  build:
    - {{ compiler('c') }}
  run:
    - python

test:
  requires:
    - python
    - setuptools
    - coverage
    - pytest
    - pytest-pep8
    - pytest-cov
    - pytest-benchmark
  imports:
    - farmhash64

about:
  home: https://github.com/tecnickcom/farmhash64
  license: MIT
