package:
  name: farmhash64
  version: 2.1.2

source:
  path: ../..

build:
  number: 1

requirements:
  host:
    - python
    - setuptools
  build:
    - {{ compiler('c') }}
  run:
    - python

test:
  requires:
    - python
    - setuptools
    - coverage
    - pytest
    - pytest-cov
    - pytest-benchmark
    - pycodestyle
  imports:
    - farmhash64

about:
  home: https://github.com/tecnickcom/farmhash64
  license: MIT
  license_file: LICENSE
  summary: Binary search for constant-lenght binary files.
