name: check

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  NODE_VERSION: '14'
  PHP_VERSION: '8.1'
  PYTHON_VERSION: '3.x'
  JAVA_VERSION: '11'
  XDEBUG_MODE: coverage

permissions:
  contents: read

jobs:
  c:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: install dependencies
        run: sudo apt install -y lcov astyle
      - name: set RELEASE number
        run: echo ${GITHUB_RUN_NUMBER} > RELEASE
      - name: test
        run: cd c && make version test build

  cgo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup go build environment
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: set RELEASE number
        run: echo ${GITHUB_RUN_NUMBER} > RELEASE
      - name: test
        run: cd cgo && make mod deps linter test GOPATH=$(go env GOPATH)

  go:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup go build environment
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: set RELEASE number
        run: echo ${GITHUB_RUN_NUMBER} > RELEASE
      - name: test
        run: cd go && make mod deps linter test GOPATH=$(go env GOPATH)

  java:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup java build environment
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.JAVA_VERSION }}
      - name: set RELEASE number
        run: echo ${GITHUB_RUN_NUMBER} > RELEASE
      - name: test
        run: cd java && make build test

  javascript:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup node build environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: install dependencies
        run: npm install --global uglify-js js-beautify
      - name: set RELEASE number
        run: echo ${GITHUB_RUN_NUMBER} > RELEASE
      - name: test
        run: cd javascript && make build

  php:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup php build environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          ini-values: display_errors=on, error_reporting=-1, zend.assertions=1
      - name: Cache module
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/
          key: composer-cache
      - name: set RELEASE number
        run: echo ${GITHUB_RUN_NUMBER} > RELEASE
      - name: test
        run: cd php && make build

  python:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup python build environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade virtualenv
      - name: set RELEASE number
        run: echo ${GITHUB_RUN_NUMBER} > RELEASE
      - name: test
        run: cd python && make vbuild

  r:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup R build environment
        uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: './r/farmhash64/'
          cache-version: 2
          extra-packages: |
            any::Rcpp
            any::devtools
            any::inline
            any::pryr
            any::renv
            any::roxygen2
            any::testthat
            any::pkgdown
      - name: set RELEASE number
        run: echo ${GITHUB_RUN_NUMBER} > RELEASE
      - name: test
        run: cd r && make build test

  rust:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: set RELEASE number
        run: echo ${GITHUB_RUN_NUMBER} > RELEASE
      - name: test
        run: cd rust && make test

  zig:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup zig build environment
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: '0.11.0'
      - name: set RELEASE number
        run: echo ${GITHUB_RUN_NUMBER} > RELEASE
      - name: test
        run: cd zig && make test
